# Generated by Django 6.0.3 on 2026-04-06 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Miqdor')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Birlik narxi')),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=18, verbose_name='Jami')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
            ],
            options={
                'verbose_name': 'Smeta qatori',
                'verbose_name_plural': 'Smeta qatorlari',
            },
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimate_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Smeta raqami')),
                ('name', models.CharField(max_length=255, verbose_name='Smeta nomi')),
                ('status', models.CharField(choices=[('DRAFT', 'Qoralama'), ('APPROVED', 'Tasdiqlangan'), ('REJECTED', 'Rad etilgan')], default='DRAFT', max_length=15, verbose_name='Holat')),
                ('total_planned', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=18, verbose_name='Jami rejalashtirilgan')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_estimates', to=settings.AUTH_USER_MODEL, verbose_name='Tasdiqlagan')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_estimates', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi')),
            ],
            options={
                'verbose_name': 'Smeta',
                'verbose_name_plural': 'Smetalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
