# Generated by Django 6.0.3 on 2026-04-06 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estimates', '0001_initial'),
        ('objects', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimates', to='objects.constructionobject', verbose_name="Ob'ekt"),
        ),
        migrations.AddField(
            model_name='estimateitem',
            name='estimate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='estimates.estimate', verbose_name='Smeta'),
        ),
        migrations.AddField(
            model_name='estimateitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Mahsulot'),
        ),
        migrations.AddField(
            model_name='estimateitem',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.unit', verbose_name="O'lchov birligi"),
        ),
    ]
