# Generated by Django 6.0.3 on 2026-04-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Buyurtma raqami')),
                ('type', models.CharField(choices=[('INCOMING', 'Kirim'), ('OUTGOING', 'Chiqim')], max_length=10, verbose_name='Turi')),
                ('customer_name', models.CharField(blank=True, max_length=255, verbose_name='Mijoz nomi')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Umumiy summa')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('status', models.CharField(choices=[('NEW', 'Yangi'), ('PROCESSING', 'Jarayonda'), ('COMPLETED', 'Bajarildi'), ('CANCELLED', 'Bekor qilindi'), ('ON_HOLD', 'Kutilmoqda')], default='NEW', max_length=15, verbose_name='Holat')),
                ('order_date', models.DateField(auto_now_add=True, verbose_name='Buyurtma sanasi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Miqdor')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Narx')),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=18, verbose_name='Jami')),
            ],
            options={
                'verbose_name': 'Buyurtma elementi',
                'verbose_name_plural': 'Buyurtma elementlari',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NEW', 'Yangi'), ('PROCESSING', 'Jarayonda'), ('COMPLETED', 'Bajarildi'), ('CANCELLED', 'Bekor qilindi'), ('ON_HOLD', 'Kutilmoqda')], max_length=15, verbose_name='Holat')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Buyurtma holat tarixi',
                'verbose_name_plural': 'Buyurtma holat tarixlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
