# Generated by Django 6.0.3 on 2026-04-08 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='barcode_scanned',
            field=models.CharField(blank=True, max_length=50, verbose_name='Skanerlangan barcode'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.category', verbose_name='Kategoriya'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='fulfilled_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Bajarilgan miqdor'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('INCOMING', 'Kirim'), ('OUTGOING', 'Chiqim')], default='OUTGOING', max_length=10, verbose_name='Turi'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Narx'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name="So'ralgan miqdor"),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=18, verbose_name='Jami'),
        ),
    ]
