# Generated by Django 6.0.3 on 2026-04-08 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_barcode_scanned_orderitem_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Yangi'), ('PROCESSING', 'Jarayonda'), ('COMPLETED', 'Bajarildi'), ('CANCELLED', 'Bekor qilindi'), ('ON_HOLD', 'Kutilmoqda'), ('DOCUMENT_ERROR', 'Hujjatda xatolik'), ('RESUBMITTED', 'Qayta yuborildi'), ('ACCEPTED', 'Qabul qilindi')], default='NEW', max_length=15, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='status',
            field=models.CharField(choices=[('NEW', 'Yangi'), ('PROCESSING', 'Jarayonda'), ('COMPLETED', 'Bajarildi'), ('CANCELLED', 'Bekor qilindi'), ('ON_HOLD', 'Kutilmoqda'), ('DOCUMENT_ERROR', 'Hujjatda xatolik'), ('RESUBMITTED', 'Qayta yuborildi'), ('ACCEPTED', 'Qabul qilindi')], max_length=15, verbose_name='Holat'),
        ),
    ]
