# Generated by Django 6.0.3 on 2026-04-08 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0003_batch_barcode'),
        ('orders', '0004_alter_order_status_alter_orderstatushistory_status'),
        ('products', '0001_initial'),
        ('warehouses', '0002_warehouse_is_main'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Vozvrat raqami')),
                ('reason', models.TextField(verbose_name='Qaytarish sababi')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('status', models.CharField(choices=[('NEW', 'Yangi'), ('ACCEPTED', 'Qabul qilindi'), ('REJECTED', 'Rad etildi'), ('RESUBMITTED', 'Qayta yuborildi')], default='NEW', max_length=15, verbose_name='Holat')),
                ('reject_note', models.TextField(blank=True, verbose_name='Rad etish sababi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='warehouses.warehouse', verbose_name='Kichik ombor')),
            ],
            options={
                'verbose_name': 'Vozvrat',
                'verbose_name_plural': 'Vozvratlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Miqdor')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_items', to='batches.batch', verbose_name='Partiya')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_items', to='products.product', verbose_name='Mahsulot')),
                ('ret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.return', verbose_name='Vozvrat')),
            ],
            options={
                'verbose_name': 'Vozvrat elementi',
                'verbose_name_plural': 'Vozvrat elementlari',
            },
        ),
    ]
