# Generated by Django 6.0.3 on 2026-04-06 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0002_initial'),
        ('products', '0001_initial'),
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Transfer raqami')),
                ('driver_name', models.CharField(blank=True, max_length=255, verbose_name='Haydovchi')),
                ('vehicle_number', models.CharField(blank=True, max_length=50, verbose_name='Mashina raqami')),
                ('status', models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('IN_TRANSIT', "Yo'lda"), ('DELIVERED', 'Yetkazildi'), ('CANCELLED', 'Bekor qilindi')], default='PENDING', max_length=15, verbose_name='Holat')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('transfer_date', models.DateField(auto_now_add=True, verbose_name='Transfer sanasi')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Yetkazilgan vaqt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi')),
                ('from_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_from', to='warehouses.warehouse', verbose_name='Qayerdan')),
                ('to_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to', to='warehouses.warehouse', verbose_name='Qayerga')),
            ],
            options={
                'verbose_name': 'Transfer',
                'verbose_name_plural': 'Transferlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Yuborilgan miqdor')),
                ('received_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Qabul qilingan miqdor')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batches.batch', verbose_name='Partiya')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Mahsulot')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transfers.transfer', verbose_name='Transfer')),
            ],
            options={
                'verbose_name': 'Transfer elementi',
                'verbose_name_plural': 'Transfer elementlari',
            },
        ),
    ]
