# Generated by Django 6.0.3 on 2026-04-06 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShotInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Faktura raqami')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Miqdor')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Narx')),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=18, verbose_name='Umumiy summa')),
                ('supplier_name', models.CharField(max_length=255, verbose_name='Yetkazib beruvchi')),
                ('document_date', models.DateField(verbose_name='Hujjat sanasi')),
                ('document_number', models.CharField(max_length=100, verbose_name='Hujjat raqami')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('status', models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('PAID', "To'langan"), ('CANCELLED', 'Bekor qilingan')], default='PENDING', max_length=15, verbose_name='Holat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='batches.batch', verbose_name='Partiya')),
            ],
            options={
                'verbose_name': 'Shot faktura',
                'verbose_name_plural': 'Shot fakturalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
