# Generated by Django 6.0.3 on 2026-04-09 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0003_batch_barcode'),
        ('invoices', '0003_shotinvoice_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shotinvoice',
            name='document_date',
        ),
        migrations.RemoveField(
            model_name='shotinvoice',
            name='document_number',
        ),
        migrations.RemoveField(
            model_name='shotinvoice',
            name='note',
        ),
        migrations.RemoveField(
            model_name='shotinvoice',
            name='price',
        ),
        migrations.RemoveField(
            model_name='shotinvoice',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='shotinvoice',
            name='status',
        ),
        migrations.RemoveField(
            model_name='shotinvoice',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='shotinvoice',
            name='supplier_name',
        ),
        migrations.RemoveField(
            model_name='shotinvoice',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='shotinvoice',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/', verbose_name='Hujjat fayli'),
        ),
        migrations.AlterField(
            model_name='shotinvoice',
            name='batch',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='batches.batch', verbose_name='Partiya'),
        ),
        migrations.AlterField(
            model_name='shotinvoice',
            name='invoice_number',
            field=models.CharField(max_length=100, verbose_name='Shot-faktura raqami'),
        ),
    ]
