# Generated by Django 6.0.3 on 2026-04-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Kompaniya nomi')),
                ('inn', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='INN/STIR')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Manzil')),
                ('contact_person', models.CharField(blank=True, max_length=255, verbose_name='Aloqa shaxsi')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Reyting')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Yetkazib beruvchi',
                'verbose_name_plural': 'Yetkazib beruvchilar',
                'ordering': ['name'],
            },
        ),
    ]
