# Generated by Django 6.0.3 on 2026-04-06 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('IN', 'Kirim'), ('OUT', 'Chiqim'), ('ADJUSTMENT', 'Tuzatish')], max_length=15, verbose_name='Turi')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Miqdor')),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Oldingi balans')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Keyingi balans')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Partiya harakati',
                'verbose_name_plural': 'Partiya harakatlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Partiya raqami')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Miqdor')),
                ('min_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Minimal miqdor')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Narx')),
                ('total_value', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=18, verbose_name='Umumiy qiymat')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('status', models.CharField(choices=[('NORMAL', 'Normal'), ('LOW', 'Kam'), ('EMPTY', "Bo'sh")], default='NORMAL', max_length=10, verbose_name='Holat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='products.product', verbose_name='Mahsulot')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='products.unit', verbose_name="O'lchov birligi")),
            ],
            options={
                'verbose_name': 'Partiya',
                'verbose_name_plural': 'Partiyalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
