# Generated by Django 6.0.3 on 2026-04-07 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, verbose_name='Shtrix kod'),
        ),
    ]
