# Generated by Django 6.0.3 on 2026-04-08 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Asosiy ombor'),
        ),
    ]
