# Generated by Django 6.0.3 on 2026-04-06 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0002_initial'),
        ('products', '0001_initial'),
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('address', models.TextField(blank=True, verbose_name='Manzil')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Tugash sanasi')),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Byudjet')),
                ('status', models.CharField(choices=[('PLANNING', 'Rejalashtirilmoqda'), ('ACTIVE', 'Faol'), ('COMPLETED', 'Tugallangan'), ('SUSPENDED', "To'xtatilgan")], default='PLANNING', max_length=15, verbose_name='Holat')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='construction_objects', to=settings.AUTH_USER_MODEL, verbose_name="Mas'ul shaxs")),
            ],
            options={
                'verbose_name': "Qurilish ob'ekti",
                'verbose_name_plural': "Qurilish ob'ektlari",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ObjectExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Miqdor')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Birlik narxi')),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=18, verbose_name='Jami summa')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_expenses', to='batches.batch', verbose_name='Partiya')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='objects.constructionobject', verbose_name="Ob'ekt")),
                ('taken_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kim oldi')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouses.warehouse', verbose_name='Ombor')),
            ],
            options={
                'verbose_name': "Ob'ekt xarajati",
                'verbose_name_plural': "Ob'ekt xarajatlari",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ObjectMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Rejalashtirilgan miqdor')),
                ('used_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Sarflangan miqdor')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='objects.constructionobject', verbose_name="Ob'ekt")),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_materials', to='products.product', verbose_name='Mahsulot')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.unit', verbose_name="O'lchov birligi")),
            ],
            options={
                'verbose_name': "Ob'ekt materiali",
                'verbose_name_plural': "Ob'ekt materiallari",
            },
        ),
    ]
