# Generated by Django 6.0.3 on 2026-04-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('LOW_STOCK', 'Kam zaxira'), ('EMPTY_STOCK', "Bo'sh zaxira"), ('ORDER', 'Buyurtma'), ('SYSTEM', 'Tizim')], max_length=20, verbose_name='Turi')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qilgan")),
                ('data', models.JSONField(blank=True, default=dict, verbose_name="Qo'shimcha ma'lumot")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bildirishnoma',
                'verbose_name_plural': 'Bildirishnomalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
